config/routes.rb
Rails.application.routes.draw do
  root "contacts#index"

  devise_for :admins

  resources :contacts, only: [:index, :show, :create]

  get "dashboard", to: "admins#index"
  delete "dashboard/delete_all", to: "admins#destroy_all"
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :full_name, presence: true
  validates :phone_num, presence: true, numericality: { only_integer: true }
  validates :shop_name, presence: true
  validates :ic_no, presence: true, numericality: { only_integer: true }, length: {is: 12}
  validates :temp, presence: true, numericality: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @contacts_grid = ContactsGrid.new(contacts_grid_params)
  end

  def destroy_all
    Contact.destroy_all

    redirect_to dashboard_path
  end

  private

  def contacts_grid_params
    params.fetch(:contacts_grid, {}).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render :index
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:full_name, :phone_num, :shop_name, :ic_no, :temp)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/index.html.erb
<div class="container-fluid my-3 min-vh-100">
  <div class="row">
    <div class="col">
      <div class="my-3 p-0">
        <h3>Dashboard</h3>
      </div>

      <div class="my-3 p-0 overflow-auto">
        <%= datagrid_table @contacts_grid, html:{ class: "table table-sm table-bordered table-striped table-hover", style: "font-size: 10pt; width: max-content;"} %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container-fluid my-3 min-vh-100">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <div>
        <%= form_with model: @contact, local: true do |f| %>
          <div class="form-group">
            <%= f.label :full_name, "Full Name (follow IC)" %>
            <%= f.text_field :full_name, placeholder: "E.g.: John Doe", class: "form-control rounded-0 #{ "is-invalid" if f.object.errors.has_key?(:full_name) }" %>
            <% if f.object.errors.has_key?(:full_name) %>
              <div class="invalid-feedback">
                <%= f.object.errors[:full_name].to_sentence.humanize %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :phone_num, "Contact Number (no \"-\")" %>
            <%= f.text_field :phone_num, placeholder: "E.g.: 0123456789", class: "form-control rounded-0 #{ "is-invalid" if f.object.errors.has_key?(:phone_num) }" %>
            <% if f.object.errors.has_key?(:phone_num) %>
              <div class="invalid-feedback">
                <%= f.object.errors[:phone_num].to_sentence.humanize %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :shop_name, "Shop Name" %>
            <%= f.text_field :shop_name, placeholder: "", class: "form-control rounded-0 #{ "is-invalid" if f.object.errors.has_key?(:shop_name) }" %>
            <% if f.object.errors.has_key?(:shop_name) %>
              <div class="invalid-feedback">
                <%= f.object.errors[:shop_name].to_sentence.humanize %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :ic_no, "IC Number (no \"-\")" %>
            <%= f.text_field :ic_no, placeholder: "E.g.: 991122331234", class: "form-control rounded-0 #{ "is-invalid" if f.object.errors.has_key?(:ic_no) }" %>
            <% if f.object.errors.has_key?(:ic_no) %>
              <div class="invalid-feedback">
                <%= f.object.errors[:ic_no].to_sentence.humanize %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.label :temp, "Temperature in Celsius" %>
            <%= f.number_field :temp, step: "0.1", placeholder: "E.g.: 37.2", class: "form-control rounded-0 #{ "is-invalid" if f.object.errors.has_key?(:temp) }" %>
            <% if f.object.errors.has_key?(:temp) %>
              <div class="invalid-feedback">
                <%= f.object.errors[:temp].to_sentence.humanize %>
              </div>
            <% end %>
          </div>

          <div class="form-group">
            <%= f.submit "Check-in", class: "btn btn-success my-3 rounded-0 w-100" %>
          </div>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/contacts/show.html.erb
<div class="container-fluid my-3 min-vh-100" style="font-size: 11pt;">

  <div class="d-flex flex-column justify-content-around align-items-center m-0 p-0" style="height: 80vh;">

    <div class="h-auto w-100 py-5 px-3 bg-success text-light text-center rounded-0">
      <h4 class="m-0 p-0">Check-in Successful</h4>
    </div>

    <div class="h-auto w-100 m-0 py-4 px-2 bg-light text-center rounded-0">
      <p class="mb-2 p-0 font-weight-bold" style="text-decoration: underline;">
        Profile :
      </p>
      <p class="m-0 p-0">
        <%= @contact.full_name %>
      </p>
      <p class="m-0 p-0"> 
        <%= @contact.ic_no %>
      </p>
      <p class="p-0">               
        <%= @contact.phone_num %>
      </p>
      

      <p class="mb-2 p-0 font-weight-bold" style="text-decoration: underline;">
        Check-in Date & Time (24 Hrs) :
      </p>
      <p class="p-0">
        <%= @contact.created_at.to_datetime.to_formatted_s(:long) %>
      </p>

      <p class="mb-2 p-0 font-weight-bold" style="text-decoration: underline;">
        Check-in Date & Time (24 Hrs) :
      </p>
      <p class="m-0 p-0">
        <%= @contact.temp %> &#8451;
      </p>
    </div>

    <div class="h-auto w-100 py-2 px-3 bg-success text-light text-center rounded-0">
      <h6 class="m-0 p-0">Thank for your cooperations</h6>
    </div>
  </div>

</div>

app/views/datagrid/_enum_checkboxes.html.erb
<%# 
Indent in this file may cause extra space to appear.
You can add indent if whitespace doesn't matter for you
%>
<%- elements.each do |value, text, checked| -%>
<%- id = [form.object_name, filter.name, value].join('_').underscore -%>
<%= form.label filter.name, options.merge(:for => id) do -%>
<%= form.check_box(filter.name, {:multiple => true, :id => id, :checked => checked, :include_hidden => false}, value.to_s, nil) -%>
<%= text -%>
<%- end -%>
<%- end -%>

app/views/datagrid/_form.html.erb
<%= form_for grid, options do |f| -%>
  <% grid.filters.each do |filter| %>
    <div class="datagrid-filter filter">
      <%= f.datagrid_label filter %>
      <%= f.datagrid_filter filter %>
    </div>
  <% end %>
  <div class="datagrid-actions">
    <%= f.submit I18n.t("datagrid.form.search").html_safe, :class => "datagrid-submit" %>
    <%# https://github.com/rails/rails/pull/14949 -%>
    <% empty_parameter = Rails.version >= "4.1.0" && Rails.version <= '4.1.2' ? nil : {}-%>
    <%= link_to I18n.t('datagrid.form.reset').html_safe, url_for(grid.to_param => empty_parameter), :class => "datagrid-reset" %>
  </div>
<% end -%>

app/views/datagrid/_head.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <th class="<%= datagrid_column_classes(grid, column) %>">
      <%= column.header %>
      <%= datagrid_order_for(grid, column, options) if column.supports_order? && options[:order]%>
    </th>
  <% end %>
</tr>

app/views/datagrid/_order_for.html.erb
<div class="order">
  <%= link_to(
      I18n.t("datagrid.table.order.asc").html_safe,
      datagrid_order_path(grid, column, false),
      :class => "asc") %>
  <%= link_to(
      I18n.t("datagrid.table.order.desc").html_safe,
      datagrid_order_path(grid, column, true),
      :class => "desc") %>
</div>

app/views/datagrid/_range_filter.html.erb
<%= form.text_field(filter.name, from_options) %>
<span class="separator <%= filter.type %>"> - </span>
<%= form.text_field(filter.name, to_options) %>

app/views/datagrid/_row.html.erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>

app/views/datagrid/_table.html.erb
<%#
Local variables:
* grid - instance of Datagrid
* assets - Array of database Entities
* options - passed options Hash
%>
<% if grid.html_columns(*options[:columns]).any? %>
  <%= content_tag :table, options[:html] do %>
    <thead>
      <%= datagrid_header(grid, options) %>
    </thead>
    <tbody>
      <% if assets.any? %>
        <%= datagrid_rows(grid, assets, options) %>
      <% else %>
        <tr><td class="noresults" colspan="100%"><%= I18n.t('datagrid.no_results').html_safe %></td></tr>
      <% end %>
    </tbody>
  <% end %>
<% else -%>
  <%= I18n.t("datagrid.table.no_columns").html_safe %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectChronicler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="author" content="Jason Tam; Freelance Software Developer; Contact me: jason6809@hotmail.com; Facebook: https://www.facebook.com/jason.tam.007; GitHub: https://github.com/Jason6809;">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand">Contact Tracing System</span>

        <% if admin_signed_in? && current_page?(dashboard_path) %>
          <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="material-icons align-text-bottom">
              settings
            </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "Change Password", edit_admin_registration_path, class: "btn btn-sm btn-info rounded-0 m-2", style: "min-width: 108px;" %>
              </li>
              <li class="nav-item">
                <%= link_to "Delete All", dashboard_delete_all_path, class: "btn btn-sm btn-warning rounded-0 m-2", style: "min-width: 128px;", data: { confirm: "Are you sure?" }, method: :delete %>
              </li>

            </ul>

            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_admin_session_path, method: :delete, class: "btn btn-sm btn-danger rounded-0 m-2", style: "min-width: 128px;" %>
              </li>
            </ul>
          </div>
        <% end %>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <div class="bg-light text-dark m-0 py-2 px-3 text-right">
        <p class="m-0 p-0" style="font-size: 10pt;">Developed By : <a href="https://www.facebook.com/jason.tam.007">Jason Tam</a></p>
      </div>
    </footer>
  </body>
</html>